name: Dreddit APK Builder

on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  apk:
    name: Setup 
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Clone source
        run: |
          git clone https://github.com/tictechtown/dreddit 
          cd dreddit
          npm install 
          npx expo prebuild 
          cd android 
          ./gradlew assembleRelease 
          zip -r ../dreddit-build.zip app/build
    
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: dreddit-build
          path: ./dreddit-build.zip
