name: Dreddit APK Builder

on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  apk:
    name: Setup 
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          
      - name: Clone source
        run: |
          git clone https://github.com/tictechtown/dreddit 
          cd dreddit
          npm install 
          npx expo prebuild 
          cd android 
          ./gradlew assembleRelease 
          mv ./android/app/build/outputs/apk/release/app-release.apk "./dreddit.apk"
    
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: ./dreddit.apk
