name: Ghostty upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync-upstream:
    runs-on: self-hosted
    steps:
      - name: Upstream the forked source
        run: |
          git clone https://${{ secrets.PAT }}@github.com/burhancodes/ghostty repo
          cd repo
          sleep 5
          git config user.name "burhanverse"
          git config user.email "contact@burhanverse.eu.org"
          sleep 5
          git remote add upstream https://github.com/ghostty-org/ghostty.git
          sleep 5
          git fetch upstream
          sleep 10
          git checkout main
          sleep 5
          git merge upstream/main
          sleep 10
          git push origin main

  update-date-file:
    runs-on: ubuntu-latest
    needs: sync-upstream
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create or update ghostty.txt
        run: |
          echo "Last updated: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" > ghostty.txt
      - name: Commit and push changes
        run: |
          git config user.name "itsnotsos"
          git config user.email "179767921+itsnotsos@users.noreply.github.com"
          git add ghostty.txt
          git commit -m "Update ghostty"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
