name: Ghostty upstream 

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  sync-upstream:
    runs-on: ubuntu-24.04

    steps:
      - name: Update the fork
        run: |
          git clone https://${{ secrets.PAT }}@github.com/burhancodes/ghostty repo
          cd repo
          sleep 10
          git config user.name "burhanverse"
          git config user.email "contact@burhanverse.eu.org"
          sleep 30
          git remote add upstream https://github.com/ghostty-org/ghostty.git
          sleep 30
          git fetch upstream
          sleep 10
          git checkout main
          sleep 10
          git merge upstream/main
          sleep 10
          git push origin main
