name: Update materialgram.spec

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  update-materialgram:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Clone spec repo
        id: clone_spec
        run: |
          git clone https://${{ secrets.PAT }}@github.com/burhancodes/materialgram-rpm spec
          cd spec
          rm -rf .git
          
      - name: Fetch latest release tag
        id: fetch_tag
        run: |
          latest_tag=$(curl -s https://api.github.com/repos/kukuruzka165/materialgram/releases/latest | jq -r .tag_name)
          if [[ -z "$latest_tag" || "$latest_tag" == "null" ]]; then
            echo "Error: Failed to fetch the latest tag." >&2
            exit 1
          fi
          echo "Latest tag: $latest_tag"
          echo "tag=${latest_tag#v}" >> $GITHUB_ENV

      - name: Check for version update
        id: check_update
        run: |
          current_version=$(grep -E '^Version:' materialgram.spec | awk '{print $2}')
          echo "Current version: $current_version"
          echo "Latest tag (sanitized): $tag"
          if [[ "$current_version" == "$tag" ]]; then
            echo "The version is up-to-date."
            echo "update_needed=false" >> $GITHUB_ENV
            exit 1
          else
            echo "A new version is available."
            echo "update_needed=true" >> $GITHUB_ENV
          fi

      - name: Update .spec file
        if: env.update_needed == 'true'
        run: |
          git clone https://${{ secrets.PAT }}@github.com/burhancodes/materialgram-rpm repo
          cd repo
          sed -i "s/^Version:.*/Version:        ${tag}/" materialgram.spec
          git config --global user.name "burhanverse"
          git config --global user.email "contact@burhanverse.eu.org"
          git add materialgram.spec
          git commit -m "Updated to version ${tag}"
          git push
