name: Update systemless-adblocker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger RPM repository dispatch event
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.sosPAT }}
          repository: Magisk-Modules-Alt-Repo/systemless-adblocker
          event-type: new-release
